import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a**2)
print(np.sin(b))

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
print(a*b)
print(a.dot(b.T))
a = np.random.random((5,5))
print(a.sum())
print(a.max())
print(a.min())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(np.sqrt(a))
print(np.square(a))
